// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Fares;
import com.nbu.fares.domain.FaresDataOnDemand;
import com.nbu.fares.domain.PromoteDataOnDemand;
import com.nbu.fares.domain.TravelDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Component;

privileged aspect FaresDataOnDemand_Roo_DataOnDemand {
    
    declare @type: FaresDataOnDemand: @Component;
    
    private Random FaresDataOnDemand.rnd = new SecureRandom();
    
    private List<Fares> FaresDataOnDemand.data;
    
    @Autowired
    PromoteDataOnDemand FaresDataOnDemand.promoteDataOnDemand;
    
    @Autowired
    TravelDataOnDemand FaresDataOnDemand.travelDataOnDemand;
    
    public Fares FaresDataOnDemand.getNewTransientFares(int index) {
        Fares obj = new Fares();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setFaresCode(obj, index);
        setPrice(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void FaresDataOnDemand.setCreatedBy(Fares obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void FaresDataOnDemand.setCreatedDate(Fares obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void FaresDataOnDemand.setFaresCode(Fares obj, int index) {
        String faresCode = "faresCode_" + index;
        obj.setFaresCode(faresCode);
    }
    
    public void FaresDataOnDemand.setPrice(Fares obj, int index) {
        Double price = new Integer(index).doubleValue();
        obj.setPrice(price);
    }
    
    public void FaresDataOnDemand.setUpdatedBy(Fares obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void FaresDataOnDemand.setUpdatedDate(Fares obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public Fares FaresDataOnDemand.getSpecificFares(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Fares obj = data.get(index);
        Long id = obj.getId();
        return Fares.findFares(id);
    }
    
    public Fares FaresDataOnDemand.getRandomFares() {
        init();
        Fares obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Fares.findFares(id);
    }
    
    public boolean FaresDataOnDemand.modifyFares(Fares obj) {
        return false;
    }
    
    public void FaresDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Fares.findFaresEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Fares' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Fares>();
        for (int i = 0; i < 10; i++) {
            Fares obj = getNewTransientFares(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
