// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.FaresDataOnDemand;
import org.springframework.beans.factory.annotation.Configurable;

privileged aspect FaresDataOnDemand_Roo_Configurable {
    
    declare @type: FaresDataOnDemand: @Configurable;
    
}
