// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Promote;
import com.nbu.fares.domain.PromoteDataOnDemand;
import com.nbu.fares.domain.PromoteIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PromoteIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PromoteIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PromoteIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: PromoteIntegrationTest: @Transactional;
    
    @Autowired
    PromoteDataOnDemand PromoteIntegrationTest.dod;
    
    @Test
    public void PromoteIntegrationTest.testCountPromotes() {
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", dod.getRandomPromote());
        long count = Promote.countPromotes();
        Assert.assertTrue("Counter for 'Promote' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PromoteIntegrationTest.testFindPromote() {
        Promote obj = dod.getRandomPromote();
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promote' failed to provide an identifier", id);
        obj = Promote.findPromote(id);
        Assert.assertNotNull("Find method for 'Promote' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Promote' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PromoteIntegrationTest.testFindAllPromotes() {
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", dod.getRandomPromote());
        long count = Promote.countPromotes();
        Assert.assertTrue("Too expensive to perform a find all test for 'Promote', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Promote> result = Promote.findAllPromotes();
        Assert.assertNotNull("Find all method for 'Promote' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Promote' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PromoteIntegrationTest.testFindPromoteEntries() {
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", dod.getRandomPromote());
        long count = Promote.countPromotes();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Promote> result = Promote.findPromoteEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Promote' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Promote' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PromoteIntegrationTest.testFlush() {
        Promote obj = dod.getRandomPromote();
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promote' failed to provide an identifier", id);
        obj = Promote.findPromote(id);
        Assert.assertNotNull("Find method for 'Promote' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPromote(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Promote' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PromoteIntegrationTest.testMergeUpdate() {
        Promote obj = dod.getRandomPromote();
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promote' failed to provide an identifier", id);
        obj = Promote.findPromote(id);
        boolean modified =  dod.modifyPromote(obj);
        Integer currentVersion = obj.getVersion();
        Promote merged = (Promote)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Promote' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PromoteIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", dod.getRandomPromote());
        Promote obj = dod.getNewTransientPromote(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Promote' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Promote' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Promote' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PromoteIntegrationTest.testRemove() {
        Promote obj = dod.getRandomPromote();
        Assert.assertNotNull("Data on demand for 'Promote' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Promote' failed to provide an identifier", id);
        obj = Promote.findPromote(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Promote' with identifier '" + id + "'", Promote.findPromote(id));
    }
    
}
