// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Promotion;
import com.nbu.fares.domain.PromotionDataOnDemand;
import java.security.SecureRandom;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.GregorianCalendar;
import java.util.Iterator;
import java.util.List;
import java.util.Random;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.springframework.stereotype.Component;

privileged aspect PromotionDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PromotionDataOnDemand: @Component;
    
    private Random PromotionDataOnDemand.rnd = new SecureRandom();
    
    private List<Promotion> PromotionDataOnDemand.data;
    
    public Promotion PromotionDataOnDemand.getNewTransientPromotion(int index) {
        Promotion obj = new Promotion();
        setCreatedBy(obj, index);
        setCreatedDate(obj, index);
        setPromotionCode(obj, index);
        setPromotionName(obj, index);
        setUpdatedBy(obj, index);
        setUpdatedDate(obj, index);
        return obj;
    }
    
    public void PromotionDataOnDemand.setCreatedBy(Promotion obj, int index) {
        String createdBy = "createdBy_" + index;
        obj.setCreatedBy(createdBy);
    }
    
    public void PromotionDataOnDemand.setCreatedDate(Promotion obj, int index) {
        Date createdDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setCreatedDate(createdDate);
    }
    
    public void PromotionDataOnDemand.setPromotionCode(Promotion obj, int index) {
        String promotionCode = "promotionCode_" + index;
        obj.setPromotionCode(promotionCode);
    }
    
    public void PromotionDataOnDemand.setPromotionName(Promotion obj, int index) {
        String promotionName = "promotionName_" + index;
        obj.setPromotionName(promotionName);
    }
    
    public void PromotionDataOnDemand.setUpdatedBy(Promotion obj, int index) {
        String updatedBy = "updatedBy_" + index;
        obj.setUpdatedBy(updatedBy);
    }
    
    public void PromotionDataOnDemand.setUpdatedDate(Promotion obj, int index) {
        Date updatedDate = new GregorianCalendar(Calendar.getInstance().get(Calendar.YEAR), Calendar.getInstance().get(Calendar.MONTH), Calendar.getInstance().get(Calendar.DAY_OF_MONTH), Calendar.getInstance().get(Calendar.HOUR_OF_DAY), Calendar.getInstance().get(Calendar.MINUTE), Calendar.getInstance().get(Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime();
        obj.setUpdatedDate(updatedDate);
    }
    
    public Promotion PromotionDataOnDemand.getSpecificPromotion(int index) {
        init();
        if (index < 0) {
            index = 0;
        }
        if (index > (data.size() - 1)) {
            index = data.size() - 1;
        }
        Promotion obj = data.get(index);
        Long id = obj.getId();
        return Promotion.findPromotion(id);
    }
    
    public Promotion PromotionDataOnDemand.getRandomPromotion() {
        init();
        Promotion obj = data.get(rnd.nextInt(data.size()));
        Long id = obj.getId();
        return Promotion.findPromotion(id);
    }
    
    public boolean PromotionDataOnDemand.modifyPromotion(Promotion obj) {
        return false;
    }
    
    public void PromotionDataOnDemand.init() {
        int from = 0;
        int to = 10;
        data = Promotion.findPromotionEntries(from, to);
        if (data == null) {
            throw new IllegalStateException("Find entries implementation for 'Promotion' illegally returned null");
        }
        if (!data.isEmpty()) {
            return;
        }
        
        data = new ArrayList<Promotion>();
        for (int i = 0; i < 10; i++) {
            Promotion obj = getNewTransientPromotion(i);
            try {
                obj.persist();
            } catch (final ConstraintViolationException e) {
                final StringBuilder msg = new StringBuilder();
                for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                    final ConstraintViolation<?> cv = iter.next();
                    msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
                }
                throw new IllegalStateException(msg.toString(), e);
            }
            obj.flush();
            data.add(obj);
        }
    }
    
}
