// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Transport;
import com.nbu.fares.domain.TransportDataOnDemand;
import com.nbu.fares.domain.TransportIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TransportIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TransportIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TransportIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TransportIntegrationTest: @Transactional;
    
    @Autowired
    TransportDataOnDemand TransportIntegrationTest.dod;
    
    @Test
    public void TransportIntegrationTest.testCountTransports() {
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", dod.getRandomTransport());
        long count = Transport.countTransports();
        Assert.assertTrue("Counter for 'Transport' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TransportIntegrationTest.testFindTransport() {
        Transport obj = dod.getRandomTransport();
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Transport' failed to provide an identifier", id);
        obj = Transport.findTransport(id);
        Assert.assertNotNull("Find method for 'Transport' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Transport' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TransportIntegrationTest.testFindAllTransports() {
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", dod.getRandomTransport());
        long count = Transport.countTransports();
        Assert.assertTrue("Too expensive to perform a find all test for 'Transport', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Transport> result = Transport.findAllTransports();
        Assert.assertNotNull("Find all method for 'Transport' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Transport' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TransportIntegrationTest.testFindTransportEntries() {
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", dod.getRandomTransport());
        long count = Transport.countTransports();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Transport> result = Transport.findTransportEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Transport' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Transport' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TransportIntegrationTest.testFlush() {
        Transport obj = dod.getRandomTransport();
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Transport' failed to provide an identifier", id);
        obj = Transport.findTransport(id);
        Assert.assertNotNull("Find method for 'Transport' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTransport(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Transport' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TransportIntegrationTest.testMergeUpdate() {
        Transport obj = dod.getRandomTransport();
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Transport' failed to provide an identifier", id);
        obj = Transport.findTransport(id);
        boolean modified =  dod.modifyTransport(obj);
        Integer currentVersion = obj.getVersion();
        Transport merged = (Transport)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Transport' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TransportIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", dod.getRandomTransport());
        Transport obj = dod.getNewTransientTransport(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Transport' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Transport' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Transport' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TransportIntegrationTest.testRemove() {
        Transport obj = dod.getRandomTransport();
        Assert.assertNotNull("Data on demand for 'Transport' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Transport' failed to provide an identifier", id);
        obj = Transport.findTransport(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Transport' with identifier '" + id + "'", Transport.findTransport(id));
    }
    
}
