// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Travel;
import com.nbu.fares.domain.TravelDataOnDemand;
import com.nbu.fares.domain.TravelIntegrationTest;
import java.util.Iterator;
import java.util.List;
import javax.validation.ConstraintViolation;
import javax.validation.ConstraintViolationException;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect TravelIntegrationTest_Roo_IntegrationTest {
    
    declare @type: TravelIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: TravelIntegrationTest: @ContextConfiguration(locations = "classpath*:/META-INF/spring/applicationContext*.xml");
    
    declare @type: TravelIntegrationTest: @Transactional;
    
    @Autowired
    TravelDataOnDemand TravelIntegrationTest.dod;
    
    @Test
    public void TravelIntegrationTest.testCountTravels() {
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", dod.getRandomTravel());
        long count = Travel.countTravels();
        Assert.assertTrue("Counter for 'Travel' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void TravelIntegrationTest.testFindTravel() {
        Travel obj = dod.getRandomTravel();
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Travel' failed to provide an identifier", id);
        obj = Travel.findTravel(id);
        Assert.assertNotNull("Find method for 'Travel' illegally returned null for id '" + id + "'", obj);
        Assert.assertEquals("Find method for 'Travel' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void TravelIntegrationTest.testFindAllTravels() {
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", dod.getRandomTravel());
        long count = Travel.countTravels();
        Assert.assertTrue("Too expensive to perform a find all test for 'Travel', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        List<Travel> result = Travel.findAllTravels();
        Assert.assertNotNull("Find all method for 'Travel' illegally returned null", result);
        Assert.assertTrue("Find all method for 'Travel' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void TravelIntegrationTest.testFindTravelEntries() {
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", dod.getRandomTravel());
        long count = Travel.countTravels();
        if (count > 20) count = 20;
        int firstResult = 0;
        int maxResults = (int) count;
        List<Travel> result = Travel.findTravelEntries(firstResult, maxResults);
        Assert.assertNotNull("Find entries method for 'Travel' illegally returned null", result);
        Assert.assertEquals("Find entries method for 'Travel' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void TravelIntegrationTest.testFlush() {
        Travel obj = dod.getRandomTravel();
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Travel' failed to provide an identifier", id);
        obj = Travel.findTravel(id);
        Assert.assertNotNull("Find method for 'Travel' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyTravel(obj);
        Integer currentVersion = obj.getVersion();
        obj.flush();
        Assert.assertTrue("Version for 'Travel' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TravelIntegrationTest.testMergeUpdate() {
        Travel obj = dod.getRandomTravel();
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Travel' failed to provide an identifier", id);
        obj = Travel.findTravel(id);
        boolean modified =  dod.modifyTravel(obj);
        Integer currentVersion = obj.getVersion();
        Travel merged = (Travel)obj.merge();
        obj.flush();
        Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        Assert.assertTrue("Version for 'Travel' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void TravelIntegrationTest.testPersist() {
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", dod.getRandomTravel());
        Travel obj = dod.getNewTransientTravel(Integer.MAX_VALUE);
        Assert.assertNotNull("Data on demand for 'Travel' failed to provide a new transient entity", obj);
        Assert.assertNull("Expected 'Travel' identifier to be null", obj.getId());
        try {
            obj.persist();
        } catch (final ConstraintViolationException e) {
            final StringBuilder msg = new StringBuilder();
            for (Iterator<ConstraintViolation<?>> iter = e.getConstraintViolations().iterator(); iter.hasNext();) {
                final ConstraintViolation<?> cv = iter.next();
                msg.append("[").append(cv.getRootBean().getClass().getName()).append(".").append(cv.getPropertyPath()).append(": ").append(cv.getMessage()).append(" (invalid value = ").append(cv.getInvalidValue()).append(")").append("]");
            }
            throw new IllegalStateException(msg.toString(), e);
        }
        obj.flush();
        Assert.assertNotNull("Expected 'Travel' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void TravelIntegrationTest.testRemove() {
        Travel obj = dod.getRandomTravel();
        Assert.assertNotNull("Data on demand for 'Travel' failed to initialize correctly", obj);
        Long id = obj.getId();
        Assert.assertNotNull("Data on demand for 'Travel' failed to provide an identifier", id);
        obj = Travel.findTravel(id);
        obj.remove();
        obj.flush();
        Assert.assertNull("Failed to remove 'Travel' with identifier '" + id + "'", Travel.findTravel(id));
    }
    
}
