// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.nbu.fares.domain;

import com.nbu.fares.domain.Travel;
import javax.persistence.Entity;

privileged aspect Travel_Roo_Jpa_Entity {
    
    declare @type: Travel: @Entity;
    
}
